version: '3.7'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "password123!"
      ACCEPT_EULA: "Y"
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
